Repository mhevyk/beauty-clinic, pull requests merged in 2024-09, with the labels that each got.

#189 Fix map warning
  src/layouts/footer/components/LocationMap.tsx
  src/layouts/footer/hooks/useMap.ts
Labels: bug

#211 Write test for removeLeadingSlashes
  tests/unit/src/utils/removeLeadingSlashes.spec.ts
Labels: tests

#207 Write tests for createFullPaths
  tests/unit/src/utils/createFullRoutePaths.spec.ts
Labels: tests

#212 Feature/180/like logic
  package-lock.json
  package.json
  src/api/graphql/getLikeDetails.graphql
  src/api/graphql/getPostById.graphql
  src/api/graphql/setLike.graphql
  src/config/apollo/links/HttpLink.ts
  src/pages/post/PostPage.tsx
  src/pages/post/components/activity-section/ActivitySection.styles.tsx
  src/pages/post/components/activity-section/ActivitySection.tsx
  src/pages/post/components/like-button/LikeButton.styles.tsx
  src/pages/post/components/like-button/LikeButton.tsx
  src/pages/post/components/like-widget/LikeWidget.tsx
  src/pages/post/components/like-widget/LikeWidgetSkeleton.tsx
  src/pages/post/components/post-footer/PostFooter.styles.tsx
  src/pages/post/components/post-footer/PostFooter.tsx
  src/pages/post/components/post-header/PostHeader.tsx
  tests/unit/mocks/mockPost.ts
  tests/unit/src/pages/post/PostPage.spec.tsx
  tests/unit/src/pages/post/components/activity-section/ActivitySection.spec.tsx
  tests/unit/src/pages/post/components/like-button/LikeButton.spec.tsx
  tests/unit/src/pages/post/components/like-widget/LikeWidget.spec.tsx
  tests/unit/src/pages/post/components/post-footer/PostFooter.spec.tsx
Labels: enhancement

#213 Reorganized test files
  tests/unit/src/components/error-boundary/ErrorBoundary.spec.tsx
  tests/unit/src/containers/modals/forgot-password-modal/ForgotPasswordModal.spec.tsx
  tests/unit/src/containers/user-toolbar/components/my-account-button/MyAccountButton.spec.tsx
  tests/unit/src/containers/user-toolbar/components/user-actions-menu-toggle/UserActionsMenuToggler.spec.tsx
  tests/unit/src/containers/user-toolbar/components/user-actions-menu/UserActionsMenu.spec.tsx
  tests/unit/src/containers/user-toolbar/utils/get-avatar-label/getAvatarLabel.spec.ts
  tests/unit/src/layouts/footer/components/ContactDetails.spec.tsx
  tests/unit/src/layouts/footer/hooks/use-delayed-unmount/useDelayedUnmount.spec.ts
  tests/unit/src/layouts/footer/hooks/use-map/useMap.spec.tsx
  tests/unit/src/layouts/footer/hooks/use-recaptcha/useRecaptcha.spec.ts
  tests/unit/src/layouts/sidebar/components/menu-links/MenuLinks.spec.tsx
  tests/unit/src/pages/book-session/BookSessionPage.spec.tsx
  tests/unit/src/pages/book-session/hooks/use-calendar/useCalendar.spec.ts
  tests/unit/src/pages/book-session/hooks/use-treatment-session-availabilities/useTreatmentSessionAvailabilities.spec.ts
  tests/unit/src/pages/book-session/utils/getMonthRange/getMonthRange.spec.ts
  tests/unit/src/pages/sign-in/SignInPage.spec.tsx
  tests/unit/src/utils/create-full-route-paths/createFullRoutePaths.spec.ts
  tests/unit/src/utils/minutes-to-hour-and-minutes/minutesToHourAndMinutes.spec.ts
  tests/unit/src/utils/remove-leading-slashes/removeLeadingSlashes.spec.ts
Labels: refactor
